baseURL = 'https://paolo-sofia.github.io/' 
languageCode = 'en-us'
theme = "JuiceBar"
title = ""

[params]
author = "Paolo Sofia"
description = "This is my Portfolio"
authorImage = "/images/profile.jpg"
paginate = 5 
Title = "Paolo Sofia Portfolio"
content = "I'm Paolo Sofia, a data scientist with a master's degree in Artificial Intelligence. Welcome!"
imageUrl = "/images/profile.jpg"

# To add a new social icon 
# More social icons can be found in JuiceBar\layouts\partials\svg.html.
[[params.social]]
name = "Github"
url = "https://github.com/paolo-sofia"
[[params.social]]
name = "email"
url = "mailto:paolosofia6@@gmail.com"

[taxonomies]
category = "categories"
tag = "tags"

# To add a new navigation link
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Projects"
url = "/project"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# If using the giscus commenting system
#[params.giscus]
#repo = "ENTER REPO HERE"
#repoID = "ENTER REPO ID HERE"
#category = "ENTER CATEGORY NAME HERE"
#categoryID = "ENTER CATEGORY ID HERE"
#mapping = "og:title"
#reactionsEnabled = "1"
#emitMetadata = "0"
#inputPosition = "bottom"
#lang = "en"
#loading = "lazy"

# Used for outputting the documentation (required).
[outputs]
home = ["HTML", "RSS", "JSON"]
